"""
JARVIS Memory Abstract Interface.

1. Why this module exists:
   Defines the contract for short-term and long-term memory operations.
   Per Version 1.0 guidelines, ONLY the interface is defined here. No concrete memory engine is implemented.

2. How it fits into the architecture:
   Sits in the Memory abstraction layer. The core orchestrator receives a `BaseMemoryStore`
   interface via dependency injection.

3. Which future modules will interact with it:
   - `backend.memory.vector_store` (Version 3.0 vector memory)
   - `backend.memory.relational_store` (Version 3.0 user preference memory)

4. Common mistakes to avoid:
   - Adding concrete database connection strings or storage code in V1.0.

5. Possible future improvements:
   - Hybrid graph and vector retrieval search signatures.
"""

from abc import ABC, abstractmethod
from typing import Any

# Forward reference or import to avoid circular dependency
# We import MemoryPipeline here for typing and initialization
from backend.memory.pipeline import MemoryPipeline


class BaseMemoryStore(ABC):
    """Abstract interface for storing and retrieving conversational context and long-term facts."""

    @abstractmethod
    def store_interaction(self, user_query: str, assistant_response: str, metadata: dict[str, Any] | None = None) -> None:
        """Saves a conversation turn to context memory."""

    @abstractmethod
    def get_recent_context(self, limit: int = 5) -> list[dict[str, Any]]:
        """Retrieves recent conversation history."""

    @abstractmethod
    def search_relevant_facts(self, query: str, top_k: int = 3) -> list[str]:
        """Performs semantic search across long-term memory facts."""


class PipelineMemoryStore(BaseMemoryStore):
    """Concrete implementation of BaseMemoryStore using the MemoryPipeline coordination flow."""

    def __init__(self, pipeline: MemoryPipeline) -> None:
        """Initialize the store with a memory pipeline.

        Args:
            pipeline: The MemoryPipeline instance to coordinate memory.
        """
        self.pipeline = pipeline
        self._recent_turns: list[dict[str, Any]] = []

    def shutdown(self) -> None:
        """Clean up memory store resources by propagating the shutdown signal."""
        if hasattr(self.pipeline, "shutdown"):
            self.pipeline.shutdown()


    def store_interaction(self, user_query: str, assistant_response: str, metadata: dict[str, Any] | None = None) -> None:
        """Saves a conversation turn to context log and runs long-term fact extraction.

        Args:
            user_query: The query sent by user.
            assistant_response: Response generated by the assistant.
            metadata: Optional additional metadata dictionary.
        """
        # 1. Store turn in recent context memory
        self._recent_turns.append({
            "user": user_query,
            "assistant": assistant_response,
            "metadata": metadata or {}
        })

        # 2. Coordinate LLM extraction & persistence
        self.pipeline.process_interaction(user_query, assistant_response)

    def get_recent_context(self, limit: int = 5) -> list[dict[str, Any]]:
        """Retrieves recent conversation history.

        Args:
            limit: Maximum number of recent conversation turns to return.

        Returns:
            list[dict[str, Any]]: List of recent conversation turn records.
        """
        return self._recent_turns[-limit:]

    def search_relevant_facts(self, query: str, top_k: int = 3) -> list[str]:
        """Performs search across stored facts/preferences, updating access timestamps.

        Args:
            query: The search query text.
            top_k: Limit on how many facts to retrieve.

        Returns:
            list[str]: String content list of matching facts.
        """
        # Recall updates last_accessed_at timestamp
        recalled = self.pipeline.manager.recall(query, limit=top_k)
        return [item.content for item in recalled]

