"""
JARVIS Memory Extractor.

1. Why this module exists:
   Extracts structured preferences and factual statements from a single conversation turn
   using the LLM provider, including metadata like importance levels and source origins.

2. How it fits into the architecture:
   Part of the memory processing pipeline. Takes conversational inputs/outputs, sends them to
   the LLM with specific prompt templates, and parses/validates the response into `ExtractedMemory` DTOs.
"""

import json
import logging
from typing import Any

from backend.ai.provider import BaseLLMProvider, MockLLMProvider
from backend.memory.models import ExtractedMemory

logger = logging.getLogger("jarvis.memory.extractor")


class MemoryExtractor:
    """Uses LLM provider to extract facts and preferences from conversational turns."""

    def __init__(self, llm_provider: BaseLLMProvider) -> None:
        """Initialize the extractor with an LLM provider.

        Args:
            llm_provider: The LLM provider instance to use for extraction.
        """
        self.llm_provider = llm_provider

    def extract_memories(self, user_input: str, assistant_response: str) -> list[ExtractedMemory]:
        """Analyzes a conversation turn to extract memorable facts and preferences.

        Args:
            user_input: Raw text command from user.
            assistant_response: Response generated by the assistant.

        Returns:
            list[ExtractedMemory]: List of validated extracted memories.
        """
        if isinstance(self.llm_provider, MockLLMProvider):
            return self._mock_extract(user_input, assistant_response)

        system_prompt = (
            "You are JARVIS's memory extraction subsystem. Your task is to analyze the conversation turn "
            "(user input and assistant response) to extract permanent facts, user preferences, or biographical "
            "details that should be remembered.\n\n"
            "Format your output as a JSON array of memory objects, where each object has:\n"
            "- 'content': a concise, third-person description of the fact or preference (e.g. 'User prefers dark mode', 'User's dog is named Max')\n"
            "- 'importance': a float ranking from 1.0 (trivial context/low value) to 5.0 (core user preference/identity details)\n"
            "- 'source': the origin of the memory. Must be one of 'user', 'assistant', or 'system'\n"
            "- 'metadata': a dictionary containing tags, category, or other relevant context.\n\n"
            "If no memorable facts are present, output an empty JSON list [].\n"
            "You must return ONLY the valid JSON list. Do not wrap it in any other JSON fields or envelope."
        )

        prompt = f"User Input: {user_input}\nAssistant Response: {assistant_response}"

        try:
            raw_response = self.llm_provider.generate_raw_completion(
                user_prompt=prompt, system_prompt=system_prompt, response_mime_type="application/json"
            )
            if not raw_response:
                return []

            # Try parsing the raw text response
            text_to_parse = raw_response.strip()
            
            # Handle potential markdown code block formatting in LLM output
            if text_to_parse.startswith("```json"):
                text_to_parse = text_to_parse.split("```json", 1)[1]
            if text_to_parse.endswith("```"):
                text_to_parse = text_to_parse.rsplit("```", 1)[0]
            text_to_parse = text_to_parse.strip()

            memories_data = json.loads(text_to_parse)

            if not isinstance(memories_data, list):
                if isinstance(memories_data, dict):
                    memories_data = [memories_data]
                else:
                    logger.warning("Parsed LLM output is not a list or dictionary: %s", raw_response)
                    return []

            extracted: list[ExtractedMemory] = []
            for item in memories_data:
                if isinstance(item, dict) and "content" in item:
                    # Validate against ExtractedMemory Pydantic model
                    importance_val = float(item.get("importance", 1.0))
                    source_val = item.get("source", "user")
                    if source_val not in ("user", "assistant", "system"):
                        source_val = "user"
                    
                    extracted.append(
                        ExtractedMemory(
                            content=str(item["content"]),
                            importance=importance_val,
                            source=source_val,
                            metadata=item.get("metadata") or {}
                        )
                    )
            return extracted

        except Exception as exc:
            logger.warning("Failed to extract memories using LLM provider: %s", exc)
            return self._fallback_parse(response.text if 'response' in locals() and response else "")

    def _mock_extract(self, user_input: str, assistant_response: str) -> list[ExtractedMemory]:
        """Provides deterministic mock extraction logic for unit testing and offline development."""
        extracted: list[ExtractedMemory] = []
        lowered = user_input.lower()

        if "my name is" in lowered:
            parts = user_input.split("my name is")
            if len(parts) > 1:
                name = parts[1].strip("? .!").title()
                extracted.append(
                    ExtractedMemory(
                        content=f"User's name is {name}.",
                        importance=5.0,
                        source="user",
                        metadata={"category": "user_profile"}
                    )
                )

        elif "i live in" in lowered:
            parts = user_input.split("i live in")
            if len(parts) > 1:
                location = parts[1].strip("? .!").title()
                extracted.append(
                    ExtractedMemory(
                        content=f"User lives in {location}.",
                        importance=4.0,
                        source="user",
                        metadata={"category": "user_profile"}
                    )
                )

        elif "i study" in lowered:
            parts = user_input.split("i study")
            if len(parts) > 1:
                subject = parts[1].strip("? .!")
                extracted.append(
                    ExtractedMemory(
                        content=f"User studies {subject}.",
                        importance=4.0,
                        source="user",
                        metadata={"category": "user_profile"}
                    )
                )

        elif "i like" in lowered:
            parts = user_input.split("i like")
            if len(parts) > 1:
                preference = parts[1].strip("? .!")
                extracted.append(
                    ExtractedMemory(
                        content=f"User likes {preference}.",
                        importance=3.0,
                        source="user",
                        metadata={"category": "preference"}
                    )
                )

        elif "remember that" in lowered:
            parts = user_input.split("remember that")
            if len(parts) > 1:
                fact = parts[1].strip("? .!")
                extracted.append(
                    ExtractedMemory(
                        content=fact,
                        importance=2.0,
                        source="user",
                        metadata={"category": "fact"}
                    )
                )

        return extracted

    def _fallback_parse(self, text: str) -> list[ExtractedMemory]:
        """Attempts to parse line-by-line list-like outputs as fallback."""
        if not text:
            return []
        extracted = []
        for line in text.splitlines():
            line = line.strip("- *• \t\"'")
            if line:
                try:
                    extracted.append(ExtractedMemory(content=line, importance=1.0, source="user"))
                except Exception:
                    pass
        return extracted
