"""
JARVIS Memory Pipeline.

1. Why this module exists:
   Acts as the central coordinator (pipeline) for processing memories.
   It orchestrates rule-based filtering (with confidence scoring and thresholds), 
   LLM-based extraction, summarization/consolidation, and final storage.

2. How it fits into the architecture:
   The orchestrator or high-level memory stores invoke `MemoryPipeline` to handle new conversation turns.
   Decouples the control flow of memory extraction from specific storage and provider implementations.
"""

import logging
from backend.ai.provider import BaseLLMProvider
from backend.memory.pre_filter import MemoryPreFilter
from backend.memory.extractor import MemoryExtractor
from backend.memory.summarizer import MemorySummarizer
from backend.memory.manager import MemoryManager
from backend.memory.models import MemoryItem

logger = logging.getLogger("jarvis.memory.pipeline")


class MemoryPipeline:
    """Coordinator orchestration class for the memory lifecycle."""

    def __init__(
        self,
        llm_provider: BaseLLMProvider,
        manager: MemoryManager | None = None,
        pre_filter: MemoryPreFilter | None = None,
        extractor: MemoryExtractor | None = None,
        summarizer: MemorySummarizer | None = None,
        prefilter_threshold: float = 0.5,
    ) -> None:
        """Initialize the pipeline with its individual components.

        Args:
            llm_provider: LLM provider instance for extractor and summarizer.
            manager: Optional MemoryManager storage component.
            pre_filter: Optional MemoryPreFilter component.
            extractor: Optional MemoryExtractor component.
            summarizer: Optional MemorySummarizer component.
            prefilter_threshold: Configurable minimum confidence (0-1) to invoke LLM.
        """
        self.llm_provider = llm_provider
        self.manager = manager or MemoryManager()
        self.pre_filter = pre_filter or MemoryPreFilter()
        self.extractor = extractor or MemoryExtractor(llm_provider=llm_provider)
        self.summarizer = summarizer or MemorySummarizer(llm_provider=llm_provider)
        self.prefilter_threshold = prefilter_threshold

        logger.info("MemoryPipeline initialized successfully with prefilter_threshold: %s", 
                    self.prefilter_threshold)

    def process_interaction(self, user_input: str, assistant_response: str) -> list[MemoryItem]:
        """Orchestrates memory extraction, validation, and storage from a turn.

        Args:
            user_input: Cleaned user input.
            assistant_response: Response generated by the assistant.

        Returns:
            list[MemoryItem]: Any new memory items that were created and stored.
        """
        logger.debug("MemoryPipeline processing interaction: '%s'", user_input)

        # 1. Lightweight pre-filter returning confidence score
        confidence = self.pre_filter.calculate_confidence(user_input)
        logger.debug("MemoryPreFilter calculated confidence: %s (Threshold: %s)", 
                     confidence, self.prefilter_threshold)

        if confidence < self.prefilter_threshold:
            logger.debug("Interaction skipped by pre-filter (confidence %s < threshold %s).", 
                         confidence, self.prefilter_threshold)
            return []

        logger.info("Interaction passed pre-filter threshold. Invoking memory extraction LLM...")

        # 2. LLM Extraction and Pydantic validation
        extracted_memories = self.extractor.extract_memories(user_input, assistant_response)
        if not extracted_memories:
            logger.debug("No new memories extracted by LLM.")
            return []

        # 3. Consolidation and deduplication against existing stored memories
        existing = self.manager.get_all()
        consolidated = self.summarizer.consolidate(existing, extracted_memories)

        if not consolidated:
            logger.debug("All extracted memories were filtered out as duplicates during consolidation.")
            return []

        # 4. Save validated memories into storage, preserving importance and source
        new_stored_items: list[MemoryItem] = []
        for mem in consolidated:
            item = MemoryItem(
                content=mem.content,
                importance=mem.importance,
                source=mem.source,
                metadata=mem.metadata
            )
            self.manager.remember(item)
            new_stored_items.append(item)

        logger.info("Successfully remembered %d new memory items.", len(new_stored_items))
        return new_stored_items
